[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11~=2.6",
    "numpy>=1.19.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "mapbox_earcut"
version = "1.0.2"
requires-python = ">=3.7"
authors = [{name = "Samuel Kogler", email = "samuel.kogler@gmail.com"}]
license =  {file = "LICENSE.md"}
description = "Python bindings for the mapbox earcut C++ polygon triangulation library."
dependencies = ["numpy>=1.19.0"]

[project.urls]
Source = "https://github.com/skogler/mapbox_earcut_python"
CSource = "https://github.com/mapbox/earcut.hpp"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools]
zip-safe = false
include-package-data = true

[project.optional-dependencies]
test = ["pytest"]


[tool.cibuildwheel]
# install the `test` extra
test-extras = ["test"]
# Run the package tests using `pytest`

test-command = "pytest {package}/tests && pip install --force-reinstall --upgrade --pre numpy && pytest {package}/tests"
test-skip = "*_arm64 *_universal2:arm64"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
